config/routes.rb
Rails.application.routes.draw do
  resources :watches
  resources :comments
  resources :achievements
  resources :user_achievements
  resources :users
  get '/signup', to: 'users#new', as: 'signup'
  resources :views
  resources :shows
  resources :seasons, only: [:show]
  resources :episodes
  resources :followings


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/search' => 'shows#search_shows'
  root 'shows#index'
  # delete 'sessions', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/TMDBApi.rb
class TMDBApi
    require 'open-uri'
    require 'json'
    def self.all_the_season_info(id)
        @show = Show.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        open("https://api.themoviedb.org/3/tv/#{id}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
            publications.read.each_line do |publication|
                @item = JSON.parse(publication)
                @show.update(num_of_seasons: @item["number_of_seasons"])
            end
        end

        @show.num_of_seasons.times do |season|
            @season_num = season + 1
            open("https://api.themoviedb.org/3/tv/#{id}/season/#{@season_num}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "show_id": @show.id,
                        "name": @item["name"],
                        "episode_count": @item["episodes"].count,
                        "overview": @item["overview"],
                        "season_number": @season_num
                    }
                    data << object
                end
                Season.create!(data)
            end
        end

    end

    def self.all_the_episodes_info(id)
        @season = Season.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        @season.episode_count.times do |episode|
            open("https://api.themoviedb.org/3/tv/#{@season.show_id}/season/#{@season.season_number}/episode/#{episode+1}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "season_id": @season.id,
                        "name": @item["name"],
                        "air_date": @item["air_date"],
                        "overview": @item["overview"],
                        "episode_number": episode+1

                    }
                    data << object
                end
                Episode.create!(data)
            end
        end
    end



end # end of api

app/models/achievement.rb
class Achievement < ApplicationRecord
    has_many :user_achievements
    has_many :users, through: :user_achievements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :episode
    belongs_to :user

end

app/models/episode.rb
class Episode < ApplicationRecord
    belongs_to :season
    has_many :comments

    has_many :watches
    has_many :users, through: :watches
end

app/models/following.rb
class Following < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
    belongs_to :show
    has_many :episodes
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :views
    has_many :users, through: :views
    has_many :seasons
    has_many :ratings

    def self.search_shows(query)
        Show.where("lower(name) LIKE ?", "%#{query.downcase}%")
    end 

    def self.check_out
        Show.all.sample(8)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :user_name, :first_name, :last_name, :age, :password, :phone_number, presence: true
    validates :phone_number, length: { is: 10 }
    validates :user_name, :phone_number, uniqueness: true

    has_many :views
    has_many :shows, through: :views
    has_many :follows
    has_many :user_achievements
    has_many :achievements, through: :user_achievements
    has_many :comments
    has_many :watches
    has_many :episodes, through: :watches

    # following
    has_many :followings
    has_many :followed_users, through: :followings

    has_many :followers, foreign_key: :followed_user_id, class_name: 'Following'
    has_many :follower_users, through: :followers, source: :user
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
    
end

app/models/view.rb
class View < ApplicationRecord
    belongs_to :user
    belongs_to :show
end

app/models/watch.rb
class Watch < ApplicationRecord
    belongs_to :user
    belongs_to :episode
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :signin]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Your Account Has Been Created Successfully!"
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:notice] = "Please Try Again"
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def show
        # byebug
        @sorted_comments = @user.comments.sort_by{|comment| comment.created_at}.reverse
    end

    def edit
        @user = User.find(params[:id])
        if @user.id != session[:user_id]
            redirect_to user_path(@user)
        end
    end

    def update
        @user.update(user_params)

        if @user.save
            flash[:notice] = "Your Information Has Been Saved!"
            redirect_to user_path
        else
            flash[:notice] = "Please Try Again"
            redirect_to new_user_path
        end
    end


    private
    
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(
            :user_name,
            :first_name,
            :last_name,
            :age,
            :password,
            :password_confirmation,
            :phone_number
        )
    end 
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_with model: @user do |f| %>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-user"></i></span>
    </div>
    <%= f.text_field :user_name, hide_label: true, placeholder: "username" , :control_class => "form-control" %>
  </div>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-address-card"></i></span>
    </div>
    <%= f.text_field :first_name, hide_label: true, placeholder: "first name" , :control_class => "form-control" %>
  </div>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-address-card"></i></span>
    </div>
    <%= f.text_field :last_name, hide_label: true, placeholder: "last name" , :control_class => "form-control" %>
  </div>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-hand-spock"></i></span>
    </div>
    <%= f.text_field :age, hide_label: true, placeholder: "age" , :control_class => "form-control" %>
  </div>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-key"></i></span>
    </div>
    <%= f.password_field :password, hide_label: true, placeholder: "password" , :control_class => "form-control"  %>
  </div>
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fas fa-key"></i></span>
    </div>
    <%= f.password_field :password, hide_label: true, placeholder: "confirm password" , :control_class => "form-control"  %>
  </div>
  <div class="form-group">
  <div class="input-group form-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><i class="fa fa-mobile"></i></span>
    </div>
    <%= f.text_field :phone_number, hide_label: true, placeholder: "phone number" , :control_class => "form-control" %>
  </div>
    <%= f.submit "Take me in!", :class => "btn float-right login_btn"%>
  </div>
<% end %>
<% if logged_in?%>
  <%= link_to "Back", user_path(@user) %>
<% end %>

app/views/users/edit.html.erb
<div class="container_a">
	<div class="d-flex justify-content-center h-100">
		<div class="card_b">
			<div class="card-header_a">
				<h3>Edit My Account</h3>
			</div>
			<div class="card-body">
        <%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container_a">
	<div class="d-flex justify-content-center h-100">
		<div class="card_b">
			<div class="card-header_a">
				<h3>Sign Up</h3>
			</div>
			<div class="card-body">
        <%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users" %>

<head>
<style>

h1 {
    text-align: center;
    padding-top: 50px;
    padding-bottom: 50px;
}

ul {
    text-align: center;
    padding: 5px;
    display: inline-block;
    vertical-align: top;
    padding-left: 100px;
    padding-right: 100px;
    
}

.profile_container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;    
}

</style>
</head>

  <body class="user">
    <h1>Profile</h1>
  <div class= "profile_container">
    <div class= "item">
      <p>Hello, <%= @user.user_name %></p>
      <p>Name: <%= @user.first_name %> <%= @user.last_name %></p>
      <p>Phone Number: <%= @user.phone_number %></p>
      <p>Age: <%= @user.age %></p>
      <p>Followers: <%= @user.followers.size%></p>
      <p>Following: <%= @user.followings.size%></p>
    </div>
    <div class= "item">
      <p>Last comments:  </p>
      <ul class="list-container">
      <% @sorted_comments.take(5).each do |comment| %>
          <li><%= link_to comment.episode.name, episode_path(comment.episode) %></li>
          <p><%= comment.comment %></p>
      <% end %>
      </ul> 
      <p>Recently Watched:  </p>
      <ul>
      <% @user.views.each do |view| %>
          <li><%= link_to view.show.name, show_path(view.show) %></li>
          <% @user.watches.each do |watch| %>
              <p><%= link_to watch.episode.name, episode_path(watch.episode) if watch.episode.season.show == view.show && watch.watched == true %></p>
          <% end %>
      <% end %>
      </ul> 
      <% if @user.id == session[:user_id]%>
        <%= button_to "Edit Account Information", {action: "edit", controller: "users", id: @user.id}, method: "get"%> 
      <% else %>
        <% if @user.followers.any?{|follow| follow.user_id == session[:user_id]} %>
          <%= button_to "Unfollow", {action: "destroy", controller: "followings"}, params:{"followee_id" => @user.id } , method: "delete"%>
        <% else %>
          <%= button_to "Follow", {action: "create", controller: "followings"}, params:{"followee_id" => @user.id } , method: "post", :class => "btn follow_btn"%>
        <% end %>
      <% end %>
    </div>
  </div>
</body>