config/routes.rb
Rails.application.routes.draw do
  resources :watches
  resources :comments
  resources :achievements
  resources :user_achievements
  resources :users
  get '/signup', to: 'users#new', as: 'signup'
  resources :views
  resources :shows
  resources :seasons, only: [:show]
  resources :episodes
  resources :followings


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/search' => 'shows#search_shows'
  root 'shows#index'
  # delete 'sessions', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/TMDBApi.rb
class TMDBApi
    require 'open-uri'
    require 'json'
    def self.all_the_season_info(id)
        @show = Show.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        open("https://api.themoviedb.org/3/tv/#{id}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
            publications.read.each_line do |publication|
                @item = JSON.parse(publication)
                @show.update(num_of_seasons: @item["number_of_seasons"])
            end
        end

        @show.num_of_seasons.times do |season|
            @season_num = season + 1
            open("https://api.themoviedb.org/3/tv/#{id}/season/#{@season_num}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "show_id": @show.id,
                        "name": @item["name"],
                        "episode_count": @item["episodes"].count,
                        "overview": @item["overview"],
                        "season_number": @season_num
                    }
                    data << object
                end
                Season.create!(data)
            end
        end

    end

    def self.all_the_episodes_info(id)
        @season = Season.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        @season.episode_count.times do |episode|
            open("https://api.themoviedb.org/3/tv/#{@season.show_id}/season/#{@season.season_number}/episode/#{episode+1}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "season_id": @season.id,
                        "name": @item["name"],
                        "air_date": @item["air_date"],
                        "overview": @item["overview"],
                        "episode_number": episode+1

                    }
                    data << object
                end
                Episode.create!(data)
            end
        end
    end



end # end of api

app/models/achievement.rb
class Achievement < ApplicationRecord
    has_many :user_achievements
    has_many :users, through: :user_achievements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :episode
    belongs_to :user

end

app/models/episode.rb
class Episode < ApplicationRecord
    belongs_to :season
    has_many :comments

    has_many :watches
    has_many :users, through: :watches
end

app/models/following.rb
class Following < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
    belongs_to :show
    has_many :episodes
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :views
    has_many :users, through: :views
    has_many :seasons
    has_many :ratings

    def self.search_shows(query)
        Show.where("lower(name) LIKE ?", "%#{query.downcase}%")
    end 

    def self.check_out
        Show.all.sample(8)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :user_name, :first_name, :last_name, :age, :password, :phone_number, presence: true
    validates :phone_number, length: { is: 10 }
    validates :user_name, :phone_number, uniqueness: true

    has_many :views
    has_many :shows, through: :views
    has_many :follows
    has_many :user_achievements
    has_many :achievements, through: :user_achievements
    has_many :comments
    has_many :watches
    has_many :episodes, through: :watches

    # following
    has_many :followings
    has_many :followed_users, through: :followings

    has_many :followers, foreign_key: :followed_user_id, class_name: 'Following'
    has_many :follower_users, through: :followers, source: :user
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
    
end

app/models/view.rb
class View < ApplicationRecord
    belongs_to :user
    belongs_to :show
end

app/models/watch.rb
class Watch < ApplicationRecord
    belongs_to :user
    belongs_to :episode
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    def index
        @shows = if params[:q] != nil
            Show.search_shows(params[:q])
         else
            Show.all.sort_by{ |show| show.created_at }
         end

        @check_out = Show.check_out
    end

    def show 
        in_database = Show.find(params[:id])
        TMDBApi.all_the_season_info(params[:id]) if !in_database.num_of_seasons
        @show = Show.find(params[:id])
        if @show.views.find{|view| view.user_id == session[:user_id]}
            @view = @show.views.find{|view| view.user_id == session[:user_id]}
        else
            @view = View.new
        end
        @seasons = @show.seasons.sort_by{ |show| show.season_number }.reverse
        @image_path  = @show.poster_path
    end

   
end
 

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/shows/index.html.erb
    <%= stylesheet_link_tag "shows" %>

<h1>Welcome to WeWatch</h1>
<ul class="container">
    <% @shows.each do |show| %>
        <li class="item">
            <%= link_to show.name, show_path(show) %>
            <p>Number of seasons: <%= show.num_of_seasons %></p>
            <p>Rating: <%= show.vote_avg %></p>
        </li>
    <% end %>
</ul>

        <!-- <div class="card-group">
            <% @check_out.each do |show| %>
        <div class="card w-75">
            <div class="contain">
            <div class="row">
                <div class="row__inner">

                <div class="tile">
                    <div class="tile__media">
                    <img class="tile__img" src="https://image.tmdb.org/t/p/w500/<%= show.poster_path %>" alt=""  />
                    </div>
                    <div class="tile__details">
                    <div class="tile__title">
                        <%= link_to show.name, show_path(show) %>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
            <% end %>
    </div> -->

app/views/shows/show.html.erb
    <%= stylesheet_link_tag "shows" %>

<body>
  <h1><%= @show.name%></h1>
      <img src="https://image.tmdb.org/t/p/w500/<%= @image_path %>" class="rounded float-right" alt="../assets/images/no_show_pic.jpg">
      <div class="season-container" >
      <%= form_with model: @view do |f| %>
          <%= f.select(:status, ["Not Watching", "Watching", "Going to watch", "Stopped Watching"], selected: @show.views.map{|view| view.status if view.user_id == session[:user_id]} )%>
          <%= f.hidden_field :show_id, value: "#{@show.id}" %>
          <%= f.hidden_field :user_id, value: "#{session[:user_id]}" %>
          <%= f.submit "Confirm" %>
      <% end %>
    <p><%= @show.overview %></p>
      <p>Number of seasons: <%= @show.num_of_seasons %></p>
      <p>Rating: <%= @show.vote_avg %></p>
  <ul class="list-container">
  <% @seasons.each do |season| %>
      <li><%= link_to season.name, season_path(season) %></li>
      <p>Number of episodes: <%= season.episode_count %></p>
  <% end %>
      </div>
  </ul>
</body>