config/routes.rb
Rails.application.routes.draw do
  resources :watches
  resources :comments
  resources :achievements
  resources :user_achievements
  resources :users
  get '/signup', to: 'users#new', as: 'signup'
  resources :views
  resources :shows
  resources :seasons, only: [:show]
  resources :episodes
  resources :followings


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/search' => 'shows#search_shows'
  root 'shows#index'
  # delete 'sessions', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/TMDBApi.rb
class TMDBApi
    require 'open-uri'
    require 'json'
    def self.all_the_season_info(id)
        @show = Show.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        open("https://api.themoviedb.org/3/tv/#{id}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
            publications.read.each_line do |publication|
                @item = JSON.parse(publication)
                @show.update(num_of_seasons: @item["number_of_seasons"])
            end
        end

        @show.num_of_seasons.times do |season|
            @season_num = season + 1
            open("https://api.themoviedb.org/3/tv/#{id}/season/#{@season_num}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "show_id": @show.id,
                        "name": @item["name"],
                        "episode_count": @item["episodes"].count,
                        "overview": @item["overview"],
                        "season_number": @season_num
                    }
                    data << object
                end
                Season.create!(data)
            end
        end

    end

    def self.all_the_episodes_info(id)
        @season = Season.find(id)
        tmdb_api_key = ENV["TMDB_API_KEY"]

        @season.episode_count.times do |episode|
            open("https://api.themoviedb.org/3/tv/#{@season.show_id}/season/#{@season.season_number}/episode/#{episode+1}?api_key=#{tmdb_api_key}&language=en-US") do |publications|
                data = []
                publications.read.each_line do |publication|
                    @item = JSON.parse(publication)
                    object = {
                        "id": @item["id"],
                        "season_id": @season.id,
                        "name": @item["name"],
                        "air_date": @item["air_date"],
                        "overview": @item["overview"],
                        "episode_number": episode+1

                    }
                    data << object
                end
                Episode.create!(data)
            end
        end
    end



end # end of api

app/models/achievement.rb
class Achievement < ApplicationRecord
    has_many :user_achievements
    has_many :users, through: :user_achievements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :episode
    belongs_to :user

end

app/models/episode.rb
class Episode < ApplicationRecord
    belongs_to :season
    has_many :comments

    has_many :watches
    has_many :users, through: :watches
end

app/models/following.rb
class Following < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
    belongs_to :show
    has_many :episodes
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :views
    has_many :users, through: :views
    has_many :seasons
    has_many :ratings

    def self.search_shows(query)
        Show.where("lower(name) LIKE ?", "%#{query.downcase}%")
    end 

    def self.check_out
        Show.all.sample(8)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :user_name, :first_name, :last_name, :age, :password, :phone_number, presence: true
    validates :phone_number, length: { is: 10 }
    validates :user_name, :phone_number, uniqueness: true

    has_many :views
    has_many :shows, through: :views
    has_many :follows
    has_many :user_achievements
    has_many :achievements, through: :user_achievements
    has_many :comments
    has_many :watches
    has_many :episodes, through: :watches

    # following
    has_many :followings
    has_many :followed_users, through: :followings

    has_many :followers, foreign_key: :followed_user_id, class_name: 'Following'
    has_many :follower_users, through: :followers, source: :user
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
    
end

app/models/view.rb
class View < ApplicationRecord
    belongs_to :user
    belongs_to :show
end

app/models/watch.rb
class Watch < ApplicationRecord
    belongs_to :user
    belongs_to :episode
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeWatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  
  <body class= "main_body">

    <div class="navbar sticky-top navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="<%= shows_path %>">WeWatch</a>
        <ul class="navbar-links" >
            <% if logged_in? %>
              <li class="nav-item"><a class="nav-link" href="<%= user_path(session[:user_id]) %>">Account</a><li>
              <li class="nav-item"><a class="nav-link" href="<%= logout_path %>" data-method="delete" style="color: white;">Log Out</a><li>
            <% else %>
              <li class="nav-item"><a class="nav-link" href="<%= login_path %>" style="color: white;">Log In</a><li>
              <li class="nav-item"><a class="nav-link" href="<%= signup_path %>" style="color: white;">Sign Up</a><li>
            <% end %>
            <li><a class="nav-link" href="<%= shows_path %>" style="color: white;">Shows</a>
            <li><a class="nav-link" href="#" style="color: white;">News</a>
        </ul>
        <%= form_tag shows_path, :method => :get, :class => "search-bar" do %>
          <div class="nav-item"><%= text_field_tag :q , "" ,  :class => "form-control_main" %></div>
          <div class="nav-item"><%= submit_tag "Search", :class => "btn btn-dark"%></div>
        <% end %>
</div>

    <%= yield %>
  </body>
</html>